import type { Member, Project, Progress } from '../types';

export const DEMO_MEMBERS: Member[] = [
  {
    id: '1',
    name: 'Eurico Alves',
    email: 'mentor@imersaoiapt.com',
    avatar_url: null,
    city: 'Lisboa',
    experience: 'avançado',
    linkedin_url: null,
    joined_at: '2026-03-01T10:00:00Z',
    imersao_num: 1,
    is_mentor: true,
    created_at: '2026-03-01T10:00:00Z',
  },
  {
    id: '2',
    name: 'Ana Ferreira',
    email: 'ana@exemplo.pt',
    avatar_url: null,
    city: 'Porto',
    experience: 'iniciante',
    linkedin_url: null,
    joined_at: '2026-03-01T11:00:00Z',
    imersao_num: 1,
    is_mentor: false,
    created_at: '2026-03-01T11:00:00Z',
  },
  {
    id: '3',
    name: 'Carlos Mendes',
    email: 'carlos@exemplo.pt',
    avatar_url: null,
    city: 'Braga',
    experience: 'intermediário',
    linkedin_url: null,
    joined_at: '2026-03-01T11:30:00Z',
    imersao_num: 1,
    is_mentor: false,
    created_at: '2026-03-01T11:30:00Z',
  },
  {
    id: '4',
    name: 'Sofia Rodrigues',
    email: 'sofia@exemplo.pt',
    avatar_url: null,
    city: 'Lisboa',
    experience: 'iniciante',
    linkedin_url: null,
    joined_at: '2026-03-01T12:00:00Z',
    imersao_num: 1,
    is_mentor: false,
    created_at: '2026-03-01T12:00:00Z',
  },
  {
    id: '5',
    name: 'João Santos',
    email: 'joao@exemplo.pt',
    avatar_url: null,
    city: 'Setúbal',
    experience: 'iniciante',
    linkedin_url: null,
    joined_at: '2026-03-01T12:30:00Z',
    imersao_num: 1,
    is_mentor: false,
    created_at: '2026-03-01T12:30:00Z',
  },
];

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'p1',
    member_id: '2',
    name: 'Gestor de Consultas',
    description: 'App para gerir consultas de nutrição e acompanhar clientes',
    pain_point: 'Perco muito tempo a gerir marcações por WhatsApp',
    github_url: 'https://github.com/ana/gestor-consultas',
    deploy_url: 'https://gestor-consultas.vercel.app',
    screenshot_url: null,
    tech_stack: ['React 19', 'Supabase', 'Vite', 'TypeScript'],
    ui_style: 'minimal',
    status: 'live',
    imersao_num: 1,
    created_at: '2026-03-02T15:00:00Z',
    member: { name: 'Ana Ferreira', avatar_url: null, city: 'Porto' },
  },
  {
    id: 'p2',
    member_id: '3',
    name: 'Menu Digital Restaurante',
    description: 'Menu digital PWA para restaurante familiar com reservas online',
    pain_point: 'Clientes não conseguem ver o menu online e ligam a perguntar',
    github_url: 'https://github.com/carlos/menu-digital',
    deploy_url: 'https://menu-digital.vercel.app',
    screenshot_url: null,
    tech_stack: ['React 19', 'PWA', 'Vite', 'TypeScript'],
    ui_style: 'gastro',
    status: 'deployed',
    imersao_num: 1,
    created_at: '2026-03-02T16:30:00Z',
    member: { name: 'Carlos Mendes', avatar_url: null, city: 'Braga' },
  },
  {
    id: 'p3',
    member_id: '4',
    name: 'Portfólio Criativo',
    description: 'Portfólio pessoal para showcasing de trabalhos de design',
    pain_point: 'Não tenho onde mostrar os meus trabalhos de forma profissional',
    github_url: null,
    deploy_url: null,
    screenshot_url: null,
    tech_stack: ['React 19', 'Vite', 'CSS Animations'],
    ui_style: 'brutalist',
    status: 'building',
    imersao_num: 1,
    created_at: '2026-03-02T18:00:00Z',
    member: { name: 'Sofia Rodrigues', avatar_url: null, city: 'Lisboa' },
  },
];

export const DEMO_PROGRESS: Progress[] = [
  {
    id: 'pr1',
    member_id: '2',
    imersao_num: 1,
    step_profiler: true,
    step_briefing: true,
    step_starter: true,
    step_optimizer: true,
    step_compiler: true,
    step_deployed: true,
    started_at: '2026-03-01T11:00:00Z',
    completed_at: '2026-03-02T15:00:00Z',
    notes: null,
    member: { name: 'Ana Ferreira', avatar_url: null, city: 'Porto', experience: 'iniciante' },
  },
  {
    id: 'pr2',
    member_id: '3',
    imersao_num: 1,
    step_profiler: true,
    step_briefing: true,
    step_starter: true,
    step_optimizer: true,
    step_compiler: true,
    step_deployed: false,
    started_at: '2026-03-01T11:30:00Z',
    completed_at: null,
    notes: 'Precisa de ajuda com o deploy na Vercel',
    member: { name: 'Carlos Mendes', avatar_url: null, city: 'Braga', experience: 'intermediário' },
  },
  {
    id: 'pr3',
    member_id: '4',
    imersao_num: 1,
    step_profiler: true,
    step_briefing: true,
    step_starter: false,
    step_optimizer: false,
    step_compiler: false,
    step_deployed: false,
    started_at: '2026-03-01T12:00:00Z',
    completed_at: null,
    notes: null,
    member: { name: 'Sofia Rodrigues', avatar_url: null, city: 'Lisboa', experience: 'iniciante' },
  },
  {
    id: 'pr4',
    member_id: '5',
    imersao_num: 1,
    step_profiler: true,
    step_briefing: false,
    step_starter: false,
    step_optimizer: false,
    step_compiler: false,
    step_deployed: false,
    started_at: '2026-03-01T12:30:00Z',
    completed_at: null,
    notes: 'Dificuldade a descrever a dor no Briefing Generator',
    member: { name: 'João Santos', avatar_url: null, city: 'Setúbal', experience: 'iniciante' },
  },
];
